apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter-notebook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: jupyter-notebook
    server: https://kubernetes.default.svc
  source:
    path: .
    repoURL: https://github.com/theJaxon/jupyter-notebook.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/volumeClaimTemplates
