apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://8gears.container-registry.com/library/n8n
    chart: n8n
    targetRevision: 1.0.0
    helm:
      values: |
        image:
          repository: docker.io/n8nio/n8n
          tag: 2.7.5-arm64        
        main:
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 2Gi
          extraEnv:
            - name: N8N_RESTRICT_FILE_ACCESS_TO
              value: "/tmp/enhancv/;/home/node/.n8n-files"
          extraVolumes:
            - name: job-mappings
              configMap:
                name: job-mappings
          extraVolumeMounts:
            - name: job-mappings
              mountPath: /tmp/enhancv
          config:
            db:
              type: sqlite
            n8n:
              personalization_enabled: "false"
              hide_usage_page: "true"
        persistence:
          enabled: true
          size: 5Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: n8n

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
