apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  project: default
  source:
    chart: ollama
    repoURL: https://helm.otwld.com/
    targetRevision: 1.2.0
    helm:
      values: |
        image:
          repository: docker.io/ollama/ollama
          tag: "0.16.1"
          pullPolicy: IfNotPresent
        ollama:
          models:
            pull:
              - deepseek-r1:8b
          gpu:
            enabled: false
        persistentVolume:
          enabled: true
          size: 15Gi
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "2Gi"
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
